project:
  type: book

book:
  title: "Introduction aux nombres complexes et polynômes"
  author: "Jérôme Soucy"
  date: "2023-07-07"
  chapters:
    - index.md
    - Arithmetique.qmd
    - Operations.qmd
    - ModuleConjugue.qmd
    - Lieux.qmd
    - exercices01.qmd
    - polaire.qmd
    - exponentielle.qmd
    - demoivre.qmd
    - racinesnieme.qmd
    - exercices02.qmd

number-sections: true
filters:
  - custom-numbered-blocks
format:
  html:
    theme: zephyr
    mainfont: Stix
    fontsize: 16pt
    toc: true
    number-sections: true
    reference-location: margin
    citation-location: margin
    bibliography: references.bib
    lang: fr
    css: "style.css"
    code-tools:
      source: false
      toggle: false
      caption: none

custom-numbered-blocks:
  groups:
    thmlike:
      colors: [AFE1AF, 228B22]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    definition:
      colors: [e1f1fd, 4663ac]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    exemple:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    remarque:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
  classes:
    Thm:
      label: "Théorème"
      group: thmlike
    Prop:
      color: green
      group: thmlike
      label: "Proposition"
    Props:
      group: thmlike
      label: "Propositions"
    Corollary:
      group: thmlike
    Conjecture:
      group: thmlike
      collapse: true  
    Def:
      label: "Définition"
      group: definition
    Ex:
      label: "Exemple"
      group: exemple
      colors: [b8cace, 134f5c]
    Rem:
      label: "Remarque"
      group: remarque
      colors: [f4cccc, cc0000]
    Rems:
      label: "Remarques"
      group: remarque
      colors: [f4cccc, cc0000]