---
title: Arithmétique élémentaire
---

{{< include _macros.qmd >}}

Avant d'introduire les nombres complexes, il serait pertinent de revoir quelques propriétés de ce que nous avons coutume d'appeler nombre, et de faire l'inventaire des objets mathématiques qui appartiennent à cette catégorie.

## Les nombres en général
Les nombres --- qu'on les qualifie de naturels, entiers, rationnels, réels ou complexes --- sont des objets mathématiques qui une fois déshabillés des attributs que nous leur prêtons, se réduisent à n'être que des ensembles. Au moyen d'efforts considérables dans certains cas, tout nombre $x$ peut s'écrire de manière à ce que $x=\{\ldots\}$, où les trois points sont eux-mêmes des ensembles, des ensembles d'ensembles, etc. Si ces définitions --- qu'on pourrait qualifier d'ensemblistes --- des nombres sont d'une importance capitale, tous conviendront que nos raisonnements quotidiens qui les font intervenir portent davantage sur leurs caractéristiques que sur leur définition. Ainsi, en pensant au nombre $2$, l'image de deux points, semblables à ceux qu'on retrouve sur un dé à 6 faces, se présentera à notre esprit plus rapidement que la définition du nombre $2$ donnée par John von Neumann (voir @art:Neumann1923) voulant que $2=\{\emptyset,\{\emptyset\}\}$, où $\emptyset$ désigne l'ensemble ne comportant aucun élément (l'ensemble vide).

## Deux opérations fondamentales
Dès le début du primaire, on apprend à additionner et à multiplier des nombres. Ils sont d'abord naturels, puis lorsque l'élève termine ses études primaires, il est réputé en mesure d'effectuer ces opérations avec des nombres appartenant à des ensembles plus vastes, comme le sont les entiers et les nombres fractionnaires[^1]. Dans tous les cas, certaines propriétés, qu'on pourrait qualifier de «&nbsp;lois de l'arithmétique&nbsp;», sont vérifiées. En voici quelques-unes :

[^1]: Éventuellement appelés nombres rationnels.

1. L'addition et la multiplication sont des opérations associatives&nbsp;;
2. L'addition et la multiplication sont des opérations commutatives&nbsp;;
3. La multiplication est distributive sur l'addition&nbsp;;
4. Un ensemble de nombres $E$ est stable pour l'addition et la multiplication.

Voici ce qu'on entend par ces lois.

## Associativité
Le fait qu'écrire $1+2+5$ ne pose aucune ambiguïté découle du fait que l'opération d'addition soit associative. Qu'on calcule $(1+2)+5$ ou $1+(2+5)$, le résultat sera le même. De la même manière, $$3\times 4\times 5=3\times (4\times 5)=(3\times 4)\times 5.$$
L'associativité c'est la possibilité de déplacer une paire de parenthèses sans modifier le résultat. Bien que l'addition et la multiplication soient des opérations associatives, le déplacement de parenthèses n'est pas forcément valable si ces deux opérations sont présentes dans un même calcul. Par exemple, pour calculer $1+2\times 5$, on ne peut pas calculer n'importe quelle des deux expressions $(1+2)\times 5$ et $1+(2\times 5)$. On *convient* que l'expression $1+2\times 5$ correspond à $1+(2\times 5)$. Il s'agit ainsi d'une convention d'écriture plutôt que d'un résultat mathématique. On réfère souvent à cette convention en invoquant la priorité des opérations. Encore une fois, ce sont des expressions qui ne font que traduire l'économie de parenthèses qu'il nous est possible de réaliser ; plutôt que d'écrire
$$1+((2\times 7)+(3\times 3-(8\times 2))),$$ on convient d'écrire simplement $1+2\times 7+3\times 3-8\times 2$. Notons que ce ne sont pas toutes les opérations qui sont associatives. Par exemple,
$$(3\div 4)\div 5\neq 3\div(4\div 5).$$
Le membre de gauche correspond à la fraction $\frac{3}{20}$ alors que le membre de droite à $\frac{15}{4}$. Il s'agit là de deux fractions qui ne sont pas équivalentes.

L'idée d'associativité s'étend au-delà des opérations sur les nombres. Par exemple, si $f,g$ et $h$ sont des fonctions, alors $(f\circ g)\circ h=f\circ (g\circ h)$. À titre d'exemple, posons $f(x)=x^2, g(x)=\sin(x)$ et $h(x)=x+1$. Nous avons que $(f\circ g)(x)=\sin^2(x)$, d'où
$$\left((f\circ g)\circ h\right)(x)=\sin^2(h(x))=\sin^2(x+1).$$
De même, $(g\circ h)(x)=\sin(x+1)$, d'où
$$\left(f\circ (g\circ h)\right)(x)=f(\sin(x+1))=(\sin(x+1))^2=\sin^2(x+1).$$
Encore une fois, l'égalité $(\sin (x+1))^2=\sin^2(x+1)$ est vraie puisqu'il s'agit d'une convention d'écriture.

## Commutativité
Si l'associativité est la possibilité de déplacer des parenthèses, la commutativité est, pour sa part, la possibilité d'inverser l'ordre des deux arguments intervenant dans l'opération. Par exemple, l'équation $$1+3=3+1$$
est vraie, puisque l'addition est une opération commutative. La multiplication de nombres est aussi une opération commutative[^2]. Il en va autrement de la multiplication matricielle. Par exemple, si
$$A=\begin{pmatrix} 0 &1 \\ 2 & 3\\ \end{pmatrix}\qquad\text{et}\qquad B=\begin{pmatrix} 1 &-1 \\ 0 & 2\\\end{pmatrix},$$
alors
$$AB=\begin{pmatrix} 0 &2 \\ 2 & 4\\ \end{pmatrix}\qquad\text{et}\qquad BA=\begin{pmatrix} -2 &-2 \\ 4 & 6\\\end{pmatrix}.$$

[^2]: Il est possible de définir une opération de multiplication sur certains ensembles de nombres, de telle sorte que la multiplication ne soit pas commutative. C'est notamment le cas avec l'ensemble des quaternions. Comme ces nombres sont l'apanage des mathématiques avancées et de la physique théorique, nous ne nous étendrons pas plus loin sur le sujet.

Un énoncé du type «&nbsp;la multiplication est commutative&nbsp;» doit donc être mis en contexte&nbsp;; il faut bien comprendre de quelle multiplication il s'agit. En principe, on doit toujours préciser l'ensemble sur lequel l'opération est définie. Il serait plus juste de dire que «&nbsp;la multiplication définie sur l'ensemble des nombres réels est une opération commutative&nbsp;» alors que «&nbsp;la multiplication définie sur l'ensemble des matrices $2\times 2$ n'est pas une opération commutative&nbsp;». L'algèbre moderne s'efforce de clarifier ces notions en introduisant ce qu'on appelle des *structures algébriques*.

## Distributivité de la multiplication par rapport à l'addition
On l'a vu, dans une même expression, il est possible d'y voir deux opérations de nature différente. Un cas important est celui d'une expression où sont présentes l'addition et la multiplication. C'est ce qu'on constate dans l'expression $5\times(1+3)$. Pour l'évaluer, on peut bien sûr évaluer la somme entre parenthèses, puis multiplier $5$ par $4$. Une autre avenue possible est de «&nbsp;distribuer&nbsp;» la multiplication par rapport à l'addition, ce qui signifie calculer $(5\times 1)+(5\times 3)$. Lorsqu'on affirme que la multiplication est distributive par rapport à l'addition, cela signifie que pour tous nombres $a,b$ et $c$, on a
$$a\times (b+c)=a\times b+a\times c.$$

## Stabilité d'un ensemble par rapport à une opération
::: {.column-margin}

::: {.callout-note}
Le symbole $\Z$, utilisé pour représenter l'ensemble des entiers, est la première lettre du mot allemand zahl qui signifie «&nbsp;nombre&nbsp;».
:::

:::

Étant donnés des nombres $a$ et $b$ appartenant à un ensemble de nombres $E$, leur somme et leur produit appartiennent toujours à l'ensemble $E$. Ce n'est pas toujours le cas pour le résultat d'une opération. À titre d'exemple, l'ensemble des nombres naturels n'est pas stable pour la soustraction. En effet, ce ne sont pas tous les problèmes de soustraction[^3] qui admettent une solution; c'est notamment le cas du problème $5+\boitevide=3$. L'ensemble des entiers règle le problème de la stabilité pour l'opération de la soustraction de nombres naturels, mais cela n'améliore guère les choses pour les problèmes de division.

[^3]: Un problème de soustraction consiste à trouver une solution à une équation de type $a+\boitevide=b$.

Prenons deux nombres naturels $a$ et $b$, tels que $b$ soit non nul, et considérons l'équation $b\times \boitevide = a$. Il arrive que cette équation possède une solution qui est dans $\N$, mais ce n'est généralement pas le cas. Par exemple, $3\times \boitevide = 12$ possède une solution ---&nbsp;le nombre $4$&nbsp;---, mais l'équation $3\times \boitevide = 13$ n'en possède pas.

::: {.column-margin}

::: {.callout-note}
L'ensemble des fractions, aussi appelé ensemble des nombres rationnels, est représenté par le symbole $\mathbb{Q}$.

L'ensemble des nombres réels est représenté par le symbole $\R$.
:::

:::


L'ajout des nombres fractionnaires permet non seulement de résoudre ce problème dans le cas où $a$ et $b$ sont des nombres naturels, *mais aussi de le faire dans le cas où $a$ et $b$ sont des nombres fractionnaires*. C'est cette propriété qu'on évoque lorsqu'on mentionne que les nombres fractionnaires sont stables pour l'opération de division.

Vers le 5ᵉ siècle avant notre ère, les mathématiciens grecs ont tenté de mesurer la longueur de l'hypoténuse d'un triangle rectangle dont les côtés adjacents à l'angle droit sont de longueur $1$. En utilisant le théorème de Pythagore, ils ont ramené le problème à celui de trouver un nombre $x$ tel que $2=x^2$. Ils en sont venus à la conclusion que $x$ ne pouvait être le quotient de deux nombres entiers. Bien sûr, le langage utilisé pour exprimer cette constatation était fort différent. On parlait plutôt d'une quantité *incommensurable*, ou encore *inexprimable*. Le tout rédigé en grec ancien! On ignore toujours si le problème du calcul de la mesure de l'hypoténuse d'un triangle rectangle est le premier qui a amené les Grecs à considérer des nombres irrationnels. Cette découverte suggère néanmoins de définir un ensemble de nombres plus vaste, comprenant le nombre $\sqrt{2}$, mais aussi tous les «&nbsp;trous&nbsp;» sur la droite numérique entre les nombres rationnels. Pour plus d'information sur le nombre $\sqrt{2}$ et l'extraction des racines carrées, voir @book:Rittaud2006. L'existence de tels nombres signifiait que les fractions ne remplissaient pas complètement la droite numérique, qu'on associe à l'ensemble des nombres réels.